Update bashrc

diff --git a/config/bashrc b/config/bashrc
--- a/config/bashrc
+++ b/config/bashrc
@@ -15,94 +15,101 @@ alias todo="todo.sh -d $TODO_DIR/todo.cfg"
 
 export TODAY="$(date +%a)"
 
-__powerline() {
-    # Colors
-    COLOR_RESET='\[\033[m\]'
-    COLOR_CWD=${COLOR_CWD:-'\[\033[0;34m\]'} # blue
-    COLOR_GIT=${COLOR_GIT:-'\[\033[0;36m\]'} # cyan
-    COLOR_SUCCESS=${COLOR_SUCCESS:-'\[\033[0;32m\]'} # green
-    COLOR_FAILURE=${COLOR_FAILURE:-'\[\033[0;31m\]'} # red
 
-    # Symbols
-    SYMBOL_GIT_BRANCH=${SYMBOL_GIT_BRANCH:-⑂}
-    SYMBOL_GIT_MODIFIED=${SYMBOL_GIT_MODIFIED:-*}
-    SYMBOL_GIT_PUSH=${SYMBOL_GIT_PUSH:-↑}
-    SYMBOL_GIT_PULL=${SYMBOL_GIT_PULL:-↓}
+function ps1_powerline {
+  RETCODE=$? # save return code
+  NUM_JOBS=$(jobs -rp | wc -l)
+  GIT_BRANCH=$(__git_ps1)
 
-    if [[ -z "$PS_SYMBOL" ]]; then
-      case "$(uname)" in
-          Darwin)   PS_SYMBOL='';;
-          Linux)    PS_SYMBOL='$';;
-          *)        PS_SYMBOL='%';;
-      esac
+  local GREY="\[\e[48;5;240m\]\[\e[38;5;250m\]"
+  local GREY_END="\[\e[48;5;2m\]\[\e[38;5;240m\]"
+
+  local GREEN="\[\e[48;5;2m\]\[\e[38;5;255m\]"
+  local GREEN_END="\[\e[48;5;27m\]\[\e[38;5;2m\]"
+
+  local ORANGE="\[\e[48;5;208m\]\[\e[38;5;255m\]"
+  local ORANGE_END="\[\e[48;5;236m\]\[\e[38;5;208m\]"
+  local ORANGE_RET_END="\[\e[48;5;160m\]\[\e[38;5;208m\]" # when next segment is prompt with return code
+
+  local BLUE="\[\e[48;5;27m\]\[\e[38;5;255m\]"
+  local BLUE_END="\[\e[48;5;208m\]\[\e[38;5;27m\]"           # when next segment is git
+  local BLUE_END_JOBS="\[\e[48;5;93m\]\[\e[38;5;27m\]"       # when next segment is jobs
+  local BLUE_END_ALT="\[\e[48;5;236m\]\[\e[38;5;27m\]"       # when next segment is prompt
+  local BLUE_END_RET="\[\e[48;5;160m\]\[\e[38;5;27m\]"       # when next segment is prompt with return code
+
+  local JOBS="\[\e[48;5;93m\]\[\e[38;5;255m\] ⏎"
+  local JOBS_END="\[\e[48;5;236m\]\[\e[38;5;93m\]"           # when next segment is prompt
+  local JOBS_NO_RET_END="\[\e[48;5;208m\]\[\e[38;5;93m\]"    # when next segment is git
+  local JOBS_NO_GIT_END="\[\e[48;5;160m\]\[\e[38;5;93m\]"    # when next segment is prompt with return code
+
+  local RET="\[\e[48;5;160m\]\[\e[38;5;255m\]"
+  local RET_END="\[\e[0m\]\[\e[38;5;160m\]\[\e[0m\] "
+
+  local PROMPT="\[\e[48;5;236m\]\[\e[38;5;255m\]"
+  local PROMPT_END="\[\e[0m\]\[\e[38;5;236m\]\[\e[0m\] "
+
+  if [ ! -w "$PWD" ]; then
+    # Current directory is not writable
+    BLUE_END="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  \[\e[48;5;208m\]\[\e[38;5;160m\]"
+    BLUE_END_JOBS="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  \[\e[48;5;93m\]\[\e[38;5;160m\]"
+    BLUE_END_ALT="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  \[\e[48;5;236m\]\[\e[38;5;160m\]"
+    BLUE_END_RET="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  "
+  fi
+
+  if [ -z "$GIT_BRANCH" ]; then
+    # Is not a git repo
+    if [ "$RETCODE" -eq 0 ]; then
+      if [ "$NUM_JOBS" -eq 0 ]; then
+        # No jobs or ret code
+        PS1="$GREY \t $GREY_END$GREEN @\h $GREEN_END$BLUE \W $BLUE_END_ALT$PROMPT \$ $PROMPT_END"
+      else
+        # no ret code but jobs
+        PS1="$GREY \t $GREY_END$GREEN @\h $GREEN_END$BLUE \W $BLUE_END_JOBS$JOBS$NUM_JOBS $JOBS_END$PROMPT \$ $PROMPT_END"
+      fi
+    else
+      if [ "$NUM_JOBS" -eq 0 ]; then
+        # No jobs but ret code is there
+        PS1="$GREY \t $GREY_END$GREEN @\h $GREEN_END$BLUE \W $BLUE_END_RET$RET \$ ⚑ $RETCODE $RET_END"
+      else
+        # Both jobs and ret code
+        PS1="$GREY \t $GREY_END$GREEN @\h $GREEN_END$BLUE \W $BLUE_END_JOBS$JOBS$NUM_JOBS $JOBS_NO_GIT_END$RET \$ ⚑ $RETCODE $RET_END"
+      fi
+    fi
+  else
+    # Is a git repo
+    local NUM_MODIFIED=$(git diff --name-only --diff-filter=M | wc -l)
+    local NUM_STAGED=$(git diff --staged --name-only --diff-filter=AM | wc -l)
+    local NUM_CONFLICT=$(git diff --name-only --diff-filter=U | wc -l)
+    local GIT_STATUS="\[\e[48;5;255m\]\[\e[38;5;208m\]\[\e[38;5;27m\] ✚$NUM_MODIFIED \[\e[38;5;208m\]\[\e[38;5;2m\] ✔$NUM_STAGED \[\e[38;5;208m\]\[\e[38;5;9m\] ✘$NUM_CONFLICT "
+    if [ "$RETCODE" -eq 0 ]; then
+      GIT_STATUS+="\[\e[38;5;255m\]\[\e[48;5;236m\]"
+    else
+      GIT_STATUS+="\[\e[38;5;255m\]\[\e[48;5;160m\]"
     fi
 
-    __git_info() { 
-        [[ $POWERLINE_GIT = 0 ]] && return # disabled
-        hash git 2>/dev/null || return # git not found
-        local git_eng="env LANG=C git"   # force git output in English to make our work easier
+    if [ "$RETCODE" -eq 0 ]; then
+      if [ "$NUM_JOBS" -eq 0 ]; then
+        # No jobs or ret code
+        PS1="$GREY \t $GREY_END$GREEN @\h $GREEN_END$BLUE \W $BLUE_END$ORANGE $GIT_BRANCH $GIT_STATUS$PROMPT \$ $PROMPT_END"
+      else
+        # no ret code but jobs
+        PS1="$GREY \t $GREY_END$GREEN @\h $GREEN_END$BLUE \W $BLUE_END_JOBS$JOBS$NUM_JOBS $JOBS_NO_RET_END$ORANGE $GIT_BRANCH $GIT_STATUS$PROMPT \$ $PROMPT_END"
+      fi
+    else
+      if [ "$NUM_JOBS" -eq 0 ]; then
+        # No jobs but ret code is there
+        PS1="$GREY \t $GREY_END$GREEN @\h $GREEN_END$BLUE \W $BLUE_END$ORANGE $GIT_BRANCH $GIT_STATUS$RET \$ ⚑ $RETCODE $RET_END"
+      else
+        # Both jobs and ret code
+        PS1="$GREY \t $GREY_END$GREEN @\h $GREEN_END$BLUE \W $BLUE_END_JOBS$JOBS$NUM_JOBS $JOBS_NO_RET_END$ORANGE $GIT_BRANCH $GIT_STATUS$RET \$ ⚑ $RETCODE $RET_END"
+      fi
+    fi
 
-        # get current branch name
-        local ref=$($git_eng symbolic-ref --short HEAD 2>/dev/null)
-
-        if [[ -n "$ref" ]]; then
-            # prepend branch symbol
-            ref=$SYMBOL_GIT_BRANCH$ref
-        else
-            # get tag name or short unique hash
-            ref=$($git_eng describe --tags --always 2>/dev/null)
-        fi
-
-        [[ -n "$ref" ]] || return  # not a git repo
-
-        local marks
-
-        # scan first two lines of output from `git status`
-        while IFS= read -r line; do
-            if [[ $line =~ ^## ]]; then # header line
-                [[ $line =~ ahead\ ([0-9]+) ]] && marks+=" $SYMBOL_GIT_PUSH${BASH_REMATCH[1]}"
-                [[ $line =~ behind\ ([0-9]+) ]] && marks+=" $SYMBOL_GIT_PULL${BASH_REMATCH[1]}"
-            else # branch is modified if output contains more lines after the header line
-                marks="$SYMBOL_GIT_MODIFIED$marks"
-                break
-            fi
-        done < <($git_eng status --porcelain --branch 2>/dev/null)  # note the space between the two <
-
-        # print the git branch segment without a trailing newline
-        printf " $ref$marks"
-    }
-
-    ps1() {
-        # Check the exit code of the previous command and display different
-        # colors in the prompt accordingly. 
-        if [ $? -eq 0 ]; then
-            local symbol="$COLOR_SUCCESS $PS_SYMBOL $COLOR_RESET"
-        else
-            local symbol="$COLOR_FAILURE $PS_SYMBOL $COLOR_RESET"
-        fi
-
-        local cwd="$COLOR_CWD\w$COLOR_RESET"
-        # Bash by default expands the content of PS1 unless promptvars is disabled.
-        # We must use another layer of reference to prevent expanding any user
-        # provided strings, which would cause security issues.
-        # POC: https://github.com/njhartwell/pw3nage
-        # Related fix in git-bash: https://github.com/git/git/blob/9d77b0405ce6b471cb5ce3a904368fc25e55643d/contrib/completion/git-prompt.sh#L324
-        if shopt -q promptvars; then
-            __powerline_git_info="$(__git_info)"
-            local git="$COLOR_GIT\${__powerline_git_info}$COLOR_RESET"
-        else
-            # promptvars is disabled. Avoid creating unnecessary env var.
-            local git="$COLOR_GIT$(__git_info)$COLOR_RESET"
-        fi
-
-        PS1="$cwd$git$symbol"
-    }
-
-    PROMPT_COMMAND="ps1${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
+  fi
 }
 
-__powerline
-unset __powerline
-
+if [  "$TERM" != "linux" ]; then
+   PROMPT_COMMAND="ps1_powerline; $PROMPT_COMMAND"
+fi
 
 
