Update bashrc

diff --git a/config/bashrc b/config/bashrc
--- a/config/bashrc
+++ b/config/bashrc
@@ -15,50 +15,30 @@ alias todo="todo.sh -d $TODO_DIR/todo.cfg"
 
 export TODAY="$(date +%a)"
 
+function __build_prompt {
+    local EXIT="$?" # store current exit code
+    
+    # define some colors
+    local RESET='\[\e[0m\]'
+    local RED='\[\e[0;31m\]'
+    local GREEN='\[\e[0;32m\]'
+    local BOLD_GRAY='\[\e[1;30m\]'
+    # longer list of codes here: https://unix.stackexchange.com/a/124408
+    
+    # start with an empty PS1
+    PS1=""
 
-function ps1_powerline {
-  RETCODE=$? # save return code
-  NUM_JOBS=$(jobs -rp | wc -l)
-
-  local GREY="\[\e[48;5;240m\]\[\e[38;5;250m\]"
-  local GREY_END="\[\e[48;5;2m\]\[\e[38;5;240m\]"
-
-  local GREEN="\[\e[48;5;2m\]\[\e[38;5;255m\]"
-  local GREEN_END="\[\e[48;5;27m\]\[\e[38;5;2m\]"
-
-  local ORANGE="\[\e[48;5;208m\]\[\e[38;5;255m\]"
-  local ORANGE_END="\[\e[48;5;236m\]\[\e[38;5;208m\]"
-  local ORANGE_RET_END="\[\e[48;5;160m\]\[\e[38;5;208m\]" # when next segment is prompt with return code
-
-  local BLUE="\[\e[48;5;27m\]\[\e[38;5;255m\]"
-  local BLUE_END_JOBS="\[\e[48;5;93m\]\[\e[38;5;27m\]"       # when next segment is jobs
-  local BLUE_END_ALT="\[\e[48;5;236m\]\[\e[38;5;27m\]"       # when next segment is prompt
-  local BLUE_END_RET="\[\e[48;5;160m\]\[\e[38;5;27m\]"       # when next segment is prompt with return code
-
-  local JOBS="\[\e[48;5;93m\]\[\e[38;5;255m\] ⏎"
-  local JOBS_END="\[\e[48;5;236m\]\[\e[38;5;93m\]"           # when next segment is prompt
-  local JOBS_NO_GIT_END="\[\e[48;5;160m\]\[\e[38;5;93m\]"    # when next segment is prompt with return code
-
-  local RET="\[\e[48;5;160m\]\[\e[38;5;255m\]"
-  local RET_END="\[\e[0m\]\[\e[38;5;160m\]\[\e[0m\] "
-
-  local PROMPT="\[\e[48;5;236m\]\[\e[38;5;255m\]"
-  local PROMPT_END="\[\e[0m\]\[\e[38;5;236m\]\[\e[0m\] "
-
-  if [ ! -w "$PWD" ]; then
-    # Current directory is not writable
-    BLUE_END="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  \[\e[48;5;208m\]\[\e[38;5;160m\]"
-    BLUE_END_JOBS="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  \[\e[48;5;93m\]\[\e[38;5;160m\]"
-    BLUE_END_ALT="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  \[\e[48;5;236m\]\[\e[38;5;160m\]"
-    BLUE_END_RET="\[\e[48;5;160m\]\[\e[38;5;27m\]\[\e[38;5;255m\]  "
-  fi
-
-  
-  PS1="$GREY \t $GREY_END$GREEN @\h $GREEN_END$BLUE \W $BLUE_END_JOBS$JOBS$NUM_JOBS \$ ⚑ $RETCODE $RET_END"
+    if [[ $EXIT -eq 0 ]]; then
+        PS1+="${GREEN}√${RESET} "      # Add green for success
+    else
+        PS1+="${RED}?️️️${EXIT}${RESET} " # Add red if exit code non 0
+    fi
+    # this is the default prompt for 
+    PS1+="${BOLD_GRAY}\[\e[48;5;93m\]\[\e[38;5;27m\]\W ${RESET}\$ "
 }
 
-if [  "$TERM" != "linux" ]; then
-   PROMPT_COMMAND="ps1_powerline; $PROMPT_COMMAND"
-fi
-
+# set the prompt command
+# include previous values to maintain Apple Terminal support (window title path and sessions)
+# this is explained in /etc/bashrc_Apple_Terminal
+PROMPT_COMMAND="__build_prompt${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
 
